### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by pashca** [0ortmann/MiniAverageDeptCalc#1]
python avCalc.py 
Please enter all names and payloads as unseparated list (eg. paul 20 frieder 10... ):  paul 2 free 3
Traceback (most recent call last):
  File "avCalc.py", line 37, in <module>
    userInput = input("Please enter all names and payloads as unseparated list (eg. paul 20 frieder 10... ):  ")
  File "<string>", line 1
    paul 2 free 3
         ^
SyntaxError: invalid syntax

**Comment by 0ortmann** [comment]
use correct python version.
